# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Build all apps
        run: |
          # Create output directory
          mkdir -p dist
          
          # Copy static files to root of dist
          if [ -d "static" ] && [ "$(ls -A static)" ]; then
            cp -r static/* dist/
          fi

          # Build each React app
          for app in react-apps/*; do
            if [ -d "$app" ]; then
              app_name=$(basename "$app")
              echo "Building $app_name..."
              cd "$app"
              
              # Install dependencies
              if [ -f "package-lock.json" ]; then
                npm ci
              else
                npm install
              fi
              
              # Build with PUBLIC_URL set to the subdirectory
              PUBLIC_URL="/ld-embeds/$app_name" npm run build || exit 1
              
              # Copy build output to dist/app_name
              mkdir -p "../../dist/$app_name"
              cp -r build/* "../../dist/$app_name/"
              cd ../..
            fi
          done
          
          echo "Built files structure:"
          find dist -type f -name "*.html" | head -20
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4